language: golang
install:
  - curl -sL https://deb.nodesource.com/setup | bash -
  - apt-get install -y nodejs
  - wget -qO- https://get.docker.com/ | sh
  - npm install -g gulp
  - npm install -g bower
  - make setup
  - go build -v ./...
script:
  - go test -v ./...
  - make errcheck
after_success:
  # TODO add web when Dockerfile is done
  - make images push
