language: golang
install:
  - curl -sL https://deb.nodesource.com/setup | bash -
  - apt-get install -y nodejs
  - apt-get install docker.io -y
  - npm install -g gulp
  - npm install -g bower
  - make setup
  - go build -v ./...
script:
  - go test -v ./...
  - make errcheck
after_success:
  - make devimages web push