site_name: Bazooka
site_url: https://github.com/bazooka-ci/bazooka/
site_description: Bazooka Documentation

repo_url: https://github.com/bazooka-ci/bazooka/

pages:
- ['index.md', 'Home']
- ['home/installation.md', 'Bazooka', 'Installation']
- ['home/developping.md', 'Bazooka', 'Developping Bazooka']
- ['home/travis.md', 'Bazooka', 'Travis Compatibility']
- ['internals/dockerindocker.md', 'Bazooka Internals', 'Docker in Docker']
- ['internals/plugin.md', 'Bazooka Internals', 'Docker as a plugin Architecture']

copyright: Copyright &copy; 2015, The Bazooka team.
