site_name: Bazooka
site_url: https://github.com/bazooka-ci/bazooka/
site_description: Bazooka Documentation

repo_url: https://github.com/bazooka-ci/bazooka/
theme_dir: 'docs/_themes'
theme: readthedocs

pages:
- ['index.md', 'Home']
- ['home/installation.md', 'Bazooka', 'Installation']
- ['home/getting_started.md', 'Bazooka', 'Getting Started']
- ['home/build_configuration.md', 'Bazooka', 'Build Configuration']
- ['home/build_lifecycle.md', 'Bazooka', 'Build Lifecycle']
- ['home/secured_variables.md', 'Bazooka', 'Secured Variables']
- ['home/permutations.md', 'Bazooka', 'Permutations']
- ['home/services.md', 'Bazooka', 'Services']
- ['home/project_configuration.md', 'Bazooka', 'Project Configuration']
- ['home/travis.md', 'Bazooka', 'Travis Compatibility']
- ['cli/service.md', 'Bazooka CLI', 'Service']
- ['languages/java.md', 'Language guides', 'Java']
- ['contribute/developping.md', 'Contribute', 'Developping Bazooka']
- ['internals/dockerindocker.md', 'Bazooka Internals', 'Docker in Docker']
- ['internals/architecture.md', 'Bazooka Internals', 'Bazooka Architecture']
- ['internals/plugin_architecture.md', 'Bazooka Internals', 'Bazooka Plugin Architecture']

copyright: Copyright &copy; 2015, The Bazooka team.
