site_name: Bazooka Documentation
repo_url: https://github.com/bazooka-ci/bazooka/
theme: readthedocs
pages:
- [index.md, Home]
- [home/installation.md, Bazooka, Installation]
- [home/developping.md, Bazooka, Developping Bazooka]
- [home/travis.md, Bazooka, Travis Compatibility]
- [internals/dockerindocker.md, Bazooka Internals, Docker in Docker]
- [internals/plugin.md, Bazooka Internals, Docker as a plugin Architecture]
