site_name: Bazooka Documentation
repo_url: https://github.com/haklop/bazooka/
theme: readthedocs
pages:
- [index.md, Home]
- [installation.md, Installation]
- [developping.md, Developping Bazooka]
- [travis.md, Travis Compatibility]
- [internals/dockerindocker.md, Bazooka Internals, Docker in Docker]
- [internals/plugin.md, Bazooka Internals, Docker as a plugin Architecture]
